name: Pull request for Go

on:
  pull_request:
    paths:
      - '**.go'
      - go.mod
      - go.sum
      - .github/workflows/pull-request-for-golang.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  LINT_VERSION: v1.58.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Test
        run: go test ./cmd/... ./pkg/...

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: ${{ env.LINT_VERSION }}
          args: -v ./cmd/... ./pkg/... ./config/...
